// 使用实际 Electron 构建产物；只在内存里写测试数据，不读取或修改用户任务。
const { app, BrowserWindow, ipcMain } = require('electron')
const fs = require('node:fs')
const path = require('node:path')
const assert = require('node:assert/strict')
const dir = __dirname
app.setPath('userData', path.join(dir, 'electron-profile'))
app.commandLine.appendSwitch('disable-renderer-backgrounding')
const sleep = ms => new Promise(r => setTimeout(r, ms))
let data, wallpaper, report
let drag = []
const checks = []
const check = (name, condition) => { assert.ok(condition, name); checks.push(name); console.log('通过：' + name) }
app.whenReady().then(async () => {
  const options = { width: 960, height: 800, show: false, frame: false, transparent: true,
    webPreferences: { backgroundThrottling: false, offscreen: true } }
  const ref = new BrowserWindow(options)
  const referencePath = process.argv[2] || 'prototype.html'
  await ref.loadFile(referencePath)
  await ref.webContents.executeJavaScript("document.getElementById('note').style.cssText = 'left:56px;top:40px';")
  data = await ref.webContents.executeJavaScript('JSON.parse(JSON.stringify(data))')
  const wallpaperHTML = await ref.webContents.executeJavaScript("document.querySelector('.wallpaper').outerHTML")
  await ref.webContents.insertCSS('#note { visibility:hidden }')
  await sleep(100)
  wallpaper = (await ref.webContents.capturePage()).toPNG().toString('base64')
  await ref.webContents.insertCSS('#note { visibility:visible }')
  await sleep(150)
  fs.writeFileSync(path.join(dir, 'prototype.png'), (await ref.webContents.capturePage()).toPNG())
  ipcMain.handle('test:get', () => data)
  ipcMain.handle('test:set', (_e, incoming) => { data = incoming })
  ipcMain.handle('test:glass', () => ({ b64: wallpaper, mime: 'image/png', win11: false,
    screenW: 960, screenH: 800, originX: 0, originY: 0, winX: 0, winY: 0 }))
  ipcMain.on('test:report', (_e, incoming) => { report = incoming })
  ipcMain.on('test:drag', (_e, incoming) => drag.push(incoming))
  const win = new BrowserWindow({ ...options, webPreferences: { ...options.webPreferences,
    preload: path.join(dir, 'preload.cjs') } })
  const errors = []
  win.webContents.on('console-message', e => { if (e.level === 'error') { errors.push(e.message); console.error(e.message) } })
  await win.loadFile(path.resolve(dir, '../../out/renderer/index.html'))
  const run = async script => { try { return await win.webContents.executeJavaScript(script) } catch (error) { console.error('失败脚本：', script);  throw error } }
  await run(`document.body.insertAdjacentHTML('afterbegin', ${JSON.stringify(wallpaperHTML)});`)
  await win.webContents.insertCSS('.wallpaper{position:fixed;inset:0;z-index:-1}.wallpaper svg{width:100%;height:100%;display:block}')
  await sleep(700)
  check('壁纸采样成功', report?.ok)
  fs.writeFileSync(path.join(dir, 'restored.png'), (await win.webContents.capturePage()).toPNG())
  check('原型尺寸与文字坐标一致', await run(`(() => { const n=document.querySelector('#note').getBoundingClientRect(); return Math.abs(n.width-320)<.1 && Math.abs(n.height-540)<.1 && Math.abs(n.x-56)<.1 && Math.abs(n.y-40)<.1 })()`))
  // 对照真实渲染后的排版，而不是只检查 CSS 源码。
  const geometryScript = `['.goal[data-kind="quarter"]','.goal[data-kind="month"]','.goal[data-kind="week"]','.divider','.task','.composer-hint'].map(s=>{const e=document.querySelector(s),r=e.getBoundingClientRect(),c=getComputedStyle(e);return {s,x:r.x,y:r.y,w:r.width,h:r.height,font:c.fontSize,weight:c.fontWeight}})`
  const expected = await ref.webContents.executeJavaScript(geometryScript)
  const actual = await run(geometryScript)
  fs.writeFileSync(path.join(dir,'geometry.json'),JSON.stringify({expected,actual},null,2))
  check('季月周、分隔线和任务排版与原型逐项相同', expected.every((e,i)=>Object.keys(e).every(k=>typeof e[k]==='number'?Math.abs(e[k]-actual[i][k])<.1:e[k]===actual[i][k])))
  await run(`document.querySelector('.goal').click(); document.querySelector('.goal-input').value='中文选字'; document.querySelector('.goal-input').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));`)
  check('选字回车不提交目标', await run("!!document.querySelector('.goal-input')"))
  await run(`document.querySelector('.goal-input').dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));document.querySelector('.composer-hint').click();document.querySelector('.composer').value='草稿保留';document.querySelector('.composer').dispatchEvent(new Event('input'));document.querySelector('.composer').dispatchEvent(new FocusEvent('blur'));document.querySelector('.composer-hint').click();`)
  check('新任务失焦草稿保留', await run("document.querySelector('.composer').value==='草稿保留'"))
  const count = data.tasks.length
  await run(`document.querySelector('.composer').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',isComposing:true,bubbles:true}));`)
  check('选字回车不添加任务', data.tasks.length===count)
  await run(`document.querySelector('.composer').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));`)
  await sleep(30)
  check('回车添加且焦点保留', data.tasks.length===count+1 && await run("document.activeElement.matches('.composer') && !document.activeElement.value"))
  await run(`document.querySelector('.composer').value='下一条';document.querySelector('.composer').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));document.querySelector('.composer').value='完成动画期间草稿';document.querySelector('.composer').dispatchEvent(new Event('input'));document.querySelector('.task .circle').click();document.querySelectorAll('.task .circle')[1].click();`)
  await sleep(1000)
  check('连续完成不丢失另一行或正在输入的草稿', data.tasks.length===count && await run("document.querySelector('.composer').value==='完成动画期间草稿'"))
  await run(`document.querySelector('.composer').dispatchEvent(new FocusEvent('blur'));document.querySelector('.task .text').dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));document.querySelector('.task-input').value='改写后完成';document.querySelector('.task-input').dispatchEvent(new FocusEvent('blur'));document.querySelector('.task .circle').click();`)
  await sleep(1000)
  check('改写后完成保持新文字', data.archive.some(t=>t.text==='改写后完成'))
  await run(`document.querySelector('.tasks').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:160,clientY:350}));Array.from(document.querySelectorAll('.menu-item')).find(e=>e.textContent==='已完成清单').click();`)
  await sleep(1200)
  check('右键入口打开已完成清单', await run("!!document.querySelector('.archive-row')"))
  fs.writeFileSync(path.join(dir, 'archive.png'), (await win.webContents.capturePage()).toPNG())
  check('清单日期不能翻过今天', await run("document.querySelectorAll('.archive-nav')[1].disabled"))
  const todayLabel = await run("document.querySelector('.archive-date').textContent")
  await run("document.querySelectorAll('.archive-nav')[0].click()")
  await sleep(400)
  check('日期前一天按钮有效', await run("document.querySelector('.archive-date').textContent") !== todayLabel)
  await run("document.querySelectorAll('.archive-nav')[1].click()")
  await sleep(600)
  check('日期后一天按钮回到今天并禁用', await run("document.querySelector('.archive-date').textContent") === todayLabel && await run("document.querySelectorAll('.archive-nav')[1].disabled"))
  await run(`window.__archiveBeforeSize=document.querySelector('.archive');document.querySelector('.archive').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:160,clientY:350}));Array.from(document.querySelectorAll('.menu-item')).find(e=>e.textContent==='字号 · 大').click();`)
  await sleep(100)
  check('清单内切换字号不摧毁容器', await run("document.querySelector('.archive')===window.__archiveBeforeSize && document.querySelector('#note').dataset.size==='large'"))
  const archiveCount = data.archive.length
  await run(`const r=document.querySelector('.archive-row');r.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));r.dispatchEvent(new MouseEvent('dblclick',{bubbles:true}));`)
  await sleep(600)
  check('双击恢复一次且清单不空白锁死', data.archive.length===archiveCount-1 && await run("!!document.querySelector('.archive-toolbar')"))
  await run(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));`)
  await sleep(800)
  check('退出清单恢复可操作的任务区', await run("!document.querySelector('.archive') && !document.querySelector('.archive-mode') && !!document.querySelector('.composer-hint')"))
  await run(`document.querySelector('.composer-hint').click();document.querySelector('.composer').value='长任务'.repeat(90);document.querySelector('.composer').dispatchEvent(new KeyboardEvent('keydown',{key:'Enter',bubbles:true}));`)
  check('长任务完整换行不受60像素截断', await run("Array.from(document.querySelectorAll('.task')).some(e=>e.offsetHeight>100 && e.scrollHeight<=e.clientHeight+1)"))
  await run(`document.querySelector('.composer').dispatchEvent(new FocusEvent('blur'));document.querySelector('.tasks').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:160,clientY:350}));document.dispatchEvent(new KeyboardEvent('keydown',{key:'ArrowDown',bubbles:true}));`)
  check('菜单可用方向键导航', await run("document.activeElement.textContent.includes('字号')"))
  await run(`document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));`)
  check('Esc关闭菜单',await run("document.querySelector('#menu').hidden"))
  await run(`document.querySelector('.tasks').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:160,clientY:350}));Array.from(document.querySelectorAll('.menu-item')).find(e=>e.textContent==='已完成清单').click();document.dispatchEvent(new KeyboardEvent('keydown',{key:'Escape',bubbles:true}));`)
  await sleep(2200)
  check('清单入场立即按Esc可安全退出', await run("!document.querySelector('.archive') && !document.querySelector('.archive-mode') && !document.querySelector('.shatter-stage')"))
  // 重载只替换本测试进程内的数据，确保空清单路径不受前面的完成操作影响。
  data.archive = []
  await win.webContents.debugger.attach('1.3')
  await win.webContents.debugger.sendCommand('Emulation.setEmulatedMedia', { features: [{ name: 'prefers-reduced-motion', value: 'reduce' }] })
  await win.reload()
  await new Promise(resolve => win.webContents.once('did-finish-load', resolve))
  await sleep(300)
  check('测试窗口已启用减少动态效果', await run("matchMedia('(prefers-reduced-motion: reduce)').matches"))
  await run(`document.querySelector('.tasks').dispatchEvent(new MouseEvent('contextmenu',{bubbles:true,clientX:160,clientY:350}));Array.from(document.querySelectorAll('.menu-item')).find(e=>e.textContent==='已完成清单').click();`)
  await sleep(100)
  check('减少动态效果时菜单打开空清单不会立即关闭', await run("!!document.querySelector('.archive-empty') && !!document.querySelector('.archive-toolbar')"))
  await run("document.querySelectorAll('.archive-nav')[2].click()")
  await sleep(100)
  check('空清单返回按钮正常退出', await run("!document.querySelector('.archive') && !!document.querySelector('.composer-hint')"))
  win.webContents.debugger.detach()
  check('渲染没有运行错误',errors.length===0)
  fs.writeFileSync(path.join(dir,'results.json'),JSON.stringify({checks,errors},null,2))
  win.destroy(); ref.destroy(); app.quit()
}).catch(error => { console.error(error); fs.writeFileSync(path.join(dir,'failure.txt'),String(error.stack)); app.exit(1) })
